// packages/wall-svelte/src/WallSection.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = HTMLAttributes<HTMLElement> & {
    animateDuration?: number | string;
    children?: Snippet;
  };

  let {
    animateDuration,
    children,
    class: className = '',
    ...rest
  }: Props = $props();
</script>

<section
  class={className}
  data-wall-animate-duration={animateDuration != null ? String(animateDuration) : undefined}
  {...rest}
>
  {@render children?.()}
</section>

// packages/wall-vue/src/WallSection.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    animateDuration?: number | string;
    class?: string | Record<string, boolean> | Array<string | Record<string, boolean>>;
    style?: string | Record<string, string>;
  }>(),
  {},
);
</script>

<template>
  <section
    :class="$props.class"
    :style="$props.style"
    :data-wall-animate-duration="
      animateDuration != null ? String(animateDuration) : undefined
    "
  >
    <slot />
  </section>
</template>
