// packages/wall-svelte/src/Wall.svelte
<script lang="ts">
  import { onDestroy, setContext } from 'svelte';
  import {
    Wall as WallCore,
    type WallEventMap,
    type WallOptions,
  } from 'wall.js';
  import { WALL_CONTEXT_KEY, type WallContextValue } from './context.js';
  import { optionsFingerprint, pickWallOptions } from './options.js';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = WallOptions &
    Omit<HTMLAttributes<HTMLDivElement>, 'onchange' | 'children'> & {
      remountKey?: string | number;
      children?: Snippet;
      onchange?: (payload: WallEventMap['change']) => void;
      onslidechange?: (payload: WallEventMap['slideChange']) => void;
      ondestroy?: () => void;
    };

  let {
    duration,
    easing,
    loop,
    loopToBottom,
    loopToTop,
    lockDocumentScroll,
    currentClass,
    animatingClass,
    sectionNavItemActiveClass,
    swipeThreshold,
    keyboard,
    wheel,
    touch,
    wrapperZIndex,
    wheelThreshold,
    wheelSkip,
    wheelSkipUnit,
    wheelSkipMax,
    wheelSkipWindow,
    skipDuration,
    swipeSkip,
    swipeSkipUnit,
    swipeSkipMax,
    remountKey,
    children,
    onchange,
    onslidechange,
    ondestroy,
    class: className = '',
    style = '',
    ...dom
  }: Props = $props();

  let el = $state<HTMLDivElement | null>(null);
  let wall = $state<WallCore | null>(null);
  let index = $state(0);
  let slideIndex = $state(0);

  const optionProps = $derived({
    duration,
    easing,
    loop,
    loopToBottom,
    loopToTop,
    lockDocumentScroll,
    currentClass,
    animatingClass,
    sectionNavItemActiveClass,
    swipeThreshold,
    keyboard,
    wheel,
    touch,
    wrapperZIndex,
    wheelThreshold,
    wheelSkip,
    wheelSkipUnit,
    wheelSkipMax,
    wheelSkipWindow,
    skipDuration,
    swipeSkip,
    swipeSkipUnit,
    swipeSkipMax,
  } satisfies WallOptions);

  const fingerprint = $derived(optionsFingerprint(optionProps));

  setContext<WallContextValue>(WALL_CONTEXT_KEY, {
    get wall() {
      return wall;
    },
    get index() {
      return index;
    },
    get slideIndex() {
      return slideIndex;
    },
  });

  $effect(() => {
    void fingerprint;
    void remountKey;
    const node = el;
    if (!node) return;

    let instance: WallCore;
    try {
      instance = new WallCore(node, pickWallOptions(optionProps));
    } catch (err) {
      console.error('[ @wall.js/svelte ] failed to create Wall', err);
      return;
    }

    wall = instance;
    index = instance.currentIndex;
    slideIndex = instance.currentSlideIndex;

    const offChange = instance.on('change', (payload) => {
      index = payload.to;
      slideIndex = instance.currentSlideIndex;
      onchange?.(payload);
    });
    const offSlide = instance.on('slideChange', (payload) => {
      slideIndex = payload.to;
      onslidechange?.(payload);
    });
    const offDestroy = instance.on('destroy', () => {
      ondestroy?.();
    });

    return () => {
      offChange();
      offSlide();
      offDestroy();
      instance.destroy();
      if (wall === instance) wall = null;
    };
  });

  onDestroy(() => {
    wall?.destroy();
    wall = null;
  });

  export function next() {
    return wall?.next() ?? Promise.resolve();
  }
  export function prev() {
    return wall?.prev() ?? Promise.resolve();
  }
  export function goTo(i: number) {
    return wall?.goTo(i) ?? Promise.resolve();
  }
  export function goToSection(n: number | string) {
    return wall?.goToSection(n) ?? Promise.resolve();
  }
  export function nextSlide() {
    return wall?.nextSlide() ?? Promise.resolve();
  }
  export function prevSlide() {
    return wall?.prevSlide() ?? Promise.resolve();
  }
  export function goToSlide(i: number) {
    return wall?.goToSlide(i) ?? Promise.resolve();
  }
  export function stepBy(delta: number) {
    return wall?.stepBy(delta) ?? Promise.resolve();
  }
  export function destroy() {
    wall?.destroy();
  }

  export function getInstance() {
    return wall;
  }
</script>

<div
  bind:this={el}
  class={['wall-js-svelte', className].filter(Boolean).join(' ')}
  style="height:100%;width:100%;{typeof style === 'string' ? style : ''}"
  {...dom}
>
  {@render children?.()}
</div>

// packages/wall-vue/src/Wall.vue
<script setup lang="ts">
import {
  computed,
  onBeforeUnmount,
  onMounted,
  provide,
  ref,
  watch,
  type PropType,
  type StyleValue,
} from 'vue';
import {
  Wall as WallCore,
  type WallEventMap,
  type WallOptions,
} from 'wall.js';
import { wallKey, type WallInstance } from './context';
import { optionsFingerprint, pickWallOptions } from './options';
import type {
  WallChangePayload,
  WallSlideChangePayload,
} from './event-types';

// Runtime props — avoids Vue SFC type-import resolution issues under TypeScript 7
const props = defineProps({
  duration: Number,
  easing: String,
  loop: Boolean,
  loopToBottom: Boolean,
  loopToTop: Boolean,
  lockDocumentScroll: Boolean,
  currentClass: String,
  animatingClass: String,
  sectionNavItemActiveClass: String,
  swipeThreshold: Number,
  keyboard: Boolean,
  wheel: Boolean,
  touch: Boolean,
  wrapperZIndex: Number,
  wheelThreshold: Number,
  wheelSkip: Boolean,
  wheelSkipUnit: Number,
  wheelSkipMax: Number,
  wheelSkipWindow: Number,
  skipDuration: Number,
  swipeSkip: Boolean,
  swipeSkipUnit: Number,
  swipeSkipMax: Number,
  remountKey: [String, Number] as PropType<string | number>,
  class: [String, Object, Array] as PropType<
    string | Record<string, boolean> | Array<string | Record<string, boolean>>
  >,
  style: [String, Object, Array] as PropType<StyleValue>,
});

const emit = defineEmits<{
  change: [payload: WallChangePayload];
  slideChange: [payload: WallSlideChangePayload];
  destroy: [];
}>();

const root = ref<HTMLElement | null>(null);
const wall = ref<WallInstance | null>(null);
const index = ref(0);
const slideIndex = ref(0);

const fingerprint = computed(() => optionsFingerprint(props as WallOptions));

function create(): void {
  if (!root.value) return;

  wall.value?.destroy();
  wall.value = null;

  let instance: WallCore;
  try {
    instance = new WallCore(root.value, pickWallOptions(props as WallOptions));
  } catch (err) {
    console.error('[ @wall.js/vue ] failed to create Wall', err);
    return;
  }

  wall.value = instance as WallInstance;
  index.value = instance.currentIndex;
  slideIndex.value = instance.currentSlideIndex;

  instance.on('change', (payload) => {
    index.value = payload.to;
    slideIndex.value = instance.currentSlideIndex;
    emit('change', payload);
  });
  instance.on('slideChange', (payload) => {
    slideIndex.value = payload.to;
    emit('slideChange', payload);
  });
  instance.on('destroy', () => {
    emit('destroy');
  });
}

onMounted(create);

onBeforeUnmount(() => {
  wall.value?.destroy();
  wall.value = null;
});

watch(
  () => [fingerprint.value, props.remountKey] as const,
  () => {
    create();
  },
);

provide(wallKey, { wall, index, slideIndex });

defineExpose({
  get instance() {
    return wall.value;
  },
  next: () => wall.value?.next() ?? Promise.resolve(),
  prev: () => wall.value?.prev() ?? Promise.resolve(),
  goTo: (i: number) => wall.value?.goTo(i) ?? Promise.resolve(),
  goToSection: (n: number | string) =>
    wall.value?.goToSection(n) ?? Promise.resolve(),
  nextSlide: () => wall.value?.nextSlide() ?? Promise.resolve(),
  prevSlide: () => wall.value?.prevSlide() ?? Promise.resolve(),
  goToSlide: (i: number) => wall.value?.goToSlide(i) ?? Promise.resolve(),
  stepBy: (delta: number) => wall.value?.stepBy(delta) ?? Promise.resolve(),
  destroy: () => wall.value?.destroy(),
  get currentIndex() {
    return wall.value?.currentIndex ?? 0;
  },
  get sectionIndex() {
    return wall.value?.sectionIndex ?? 1;
  },
  get currentSlideIndex() {
    return wall.value?.currentSlideIndex ?? 0;
  },
  get sectionCount() {
    return wall.value?.sectionCount ?? 0;
  },
  get isAnimating() {
    return wall.value?.isAnimating ?? false;
  },
});
</script>

<template>
  <div
    ref="root"
    class="wall-js-vue"
    :class="props.class"
    :style="[{ height: '100%', width: '100%' }, props.style]"
  >
    <slot />
  </div>
</template>
